name: Descargas Diarias

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]

  schedule:
    - cron:  '0 1 * * *'
    - cron:  '0 4 * * *'
    - cron:  '0 7 * * *'
    - cron:  '0 10 * * *'
    - cron:  '0 13 * * *'
    - cron:  '0 16 * * *'
    - cron:  '0 19 * * *'
    - cron:  '0 22 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

        
    - name: AUTOMATIZACIÓN
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        python automatizacion.py
        python automatizacion_24h.py
        python automatizacion_48h.py
        python automatizacion_diaria.py
        python Incendios_24h/automatizacion_h.py
        python Incendios_24h/automatizacion_24h.py      
               
        

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Actualizacion"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        # commit_user_email: gholley42@gmail.com
        # commit_author: DataIntelligence BOT <gholley42@gmail.com>

        commit_user_email: lmonsalve22@gmail.com
        commit_author: DataIntelligence BOT <lmonsalve22@gmail.com>

        push_options: '--force'
